version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      NODE_ENV: development
      JWT_SECRET: 1hard_to_guess_secret7890a
      PORT: 3000
    ports:
      - "8080:3000"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'xprop'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      
volumes:
  db:
    driver: local